[package]
name = "dingir-exchange"
version = "0.1.0"
authors = ["lispczz <mycinbrin@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
config_rs = { package = "config", version = "0.10.1" }
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
prost = "0.6.1"
prost-types = "0.6.1"
bytes = "0.5.4"

futures-core = { version = "0.3.5", default-features = false }
futures-channel = "0.3.5"
futures-util = { version = "0.3.5", default-features = false }

tokio = { version = "0.2.21", features = ["full"] }
thread-id = "3.3.0"
futures = "0.3.5"
hyper = "0.13.6"
crossbeam-channel = "0.4.2"
rdkafka = "0.23.1"
nix = "0.17.0"
anyhow = "1.0.31"
diesel = { version = "1.4.4", features = ["numeric", "unstable", "chrono", "postgres", "serde_json", "bigdecimal"] }
diesel_migrations = "1.4.0"
chrono = "0.4.11"
rust_decimal = { version = "1.6.0", features = ["postgres", "diesel", "bytes", "byteorder"] }
rust_decimal_macros = "1.6.0"

tonic = "0.2.1"
ttl_cache = "0.5.1"
itertools = "0.9.0"
dotenv = "0.15.0"
bigdecimal = "0.1.2"
num_enum = "0.5.0"

[build-dependencies]
tonic-build = "0.2.0"
prost = "0.6.1"
