debug: true
db_log: postgres://exchange:exchange_AA9944@exchange-pq/exchange
db_history: postgres://exchange:exchange_AA9944@exchange-pq/exchange
brokers: exchange-kafka.dingir-exchange:9092
slice_interval: 3600
slice_keeptime: 259200
disable_self_trade: true
disable_market_order: true
check_eddsa_signatue: auto
user_order_num_limit: 1000
